import React from 'react'
import PropTypes from 'prop-types';
import * as V from 'victory';
import 'antd/dist/antd.css';
import { Progress } from 'antd';

const averageFootprint = 100;

class Footprint extends React.Component {

  render() {    
    return (
      <div id='footprint'>
        <h1>Your Footprint</h1>
        <p>The average footprint in your country 
          is around 10 tonnes of CO2. Your footprint 
          is above average. Let's reduce it together!</p>
          <div className='graph'>
            <h2>Current Footprint: {this.props.emissions}kg of CO2</h2>
            <Progress percent={this.props.emissions / 10} status="exception" showInfo={false}/>

            <h2>Average Footprint: {averageFootprint}kg of CO2</h2>
            <Progress percent={averageFootprint / 10} showInfo={false}/>

            <h2>In order to stop climate change, this is the maximum amount of CO2 that can be generated by a single person in a month: 50kg of CO2</h2>
            <Progress percent={0.5} showInfo={false}></Progress>
          </div>
            {/* <V.VictoryBar data={currentEmissions} 
                          x="x"
                          y="carbon"
                          labels={["current footprint", "average footprint"]}
            ></V.VictoryBar>


            <h3>Emissions History</h3>
            <V.VictoryChart scale={{ x: "month" }} width={400} height={400}>
            <V.VictoryStack colorScale="warm">
              <V.VictoryGroup
                data={data}
                interpolation="natural"
                // data accessor for x values
                x="month"
                // data accessor for y values
                y="before"
              >
                <V.VictoryArea/>
                <V.VictoryPortal>
                  <V.VictoryScatter
                    style={{ data: { fill: "black" } }}
                  />
                </V.VictoryPortal>
              </V.VictoryGroup>
              <V.VictoryGroup
                data={data}
                interpolation="natural"
                // data accessor for x values
                x="month"
                // data accessor for y values
                y="after"
              >
                <V.VictoryArea/>
                <V.VictoryPortal>
                  <V.VictoryScatter
                    style={{ data: { fill: "black" } }}
                  />
                </V.VictoryPortal>
              </V.VictoryGroup>
            </V.VictoryStack>
          </V.VictoryChart> */}
      </div>
    )
  }
}

Footprint.propTypes = {
  carbonData: PropTypes.array,
  emissions: PropTypes.number,
};

export default Footprint